plugins {
	id 'java'
	id 'org.springframework.boot' version '3.1.4'
	id 'io.spring.dependency-management' version '1.1.3'
}

group = 'com.uaa.demo'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	// https://mvnrepository.com/artifact/com.itextpdf/itextpdf
	implementation 'com.itextpdf:itextpdf:5.0.6'
	implementation 'com.itextpdf:itext7-core:7.2.5'
	// https://mvnrepository.com/artifact/org.apache.poi/poi
	implementation 'org.apache.poi:poi:4.1.1'
// https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml
	implementation 'org.apache.poi:poi-ooxml:4.1.1'

	implementation 'com.google.zxing:core:3.5.1'

	implementation 'org.apache.pdfbox:pdfbox:2.0.29'


	// Apache Commons IO для работы с файлами
	implementation 'commons-io:commons-io:2.11.0'

	implementation 'org.ghost4j:ghost4j:1.0.1'


	// https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
	implementation 'org.apache.commons:commons-lang3:3.12.0'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'org.springframework.boot:spring-boot-maven-plugin:3.1.4'


	implementation 'org.jsoup:jsoup:1.14.3'
}

tasks.named('test') {
	useJUnitPlatform()
}
